version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - uploads_data:/app/uploads
    environment:
      - NODE_ENV=production

volumes:
  uploads_data:
    name: motonapratica_uploads_data
